version: 2

jobs:
  build-and-test:
    docker:
      - image: cypress/base:8:0:0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm serv & cypress run tst_spec.js
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test
