version: 2.1
orbs:
  node: cypress/base:8:0:0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm serv & cypress run tst_spec.js
workflows:
    build-and-test:
      jobs:
        - build-and-test
