version: 2

jobs:
  build-and-test:
    docker:
      - image: cypress/browsers:node8.9.3-npm6.10.1-chrome75
    steps:
      - checkout
      - run:
          name: Setup Node.js via nvm
          command: |
            curl --silent -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo 'source "$NVM_DIR/nvm.sh" --no-use' >> $BASH_ENV
            source $BASH_ENV
            nvm install 0.10.26 --no-progress
            nvm alias default 0.10.26
            sed -i -e 's/ --no-use//' $BASH_ENV
      - run:
          name: Verify
          command: node -v && npm -v
      - restore_cache:
          keys:
          - v2-dep-sgk_web-{{ checksum "package.json" }}
      - run: npm install
      - run: nvm install 8.9.3 && nvm alias default 8.9.3
      - run: npm install -g cypress@^4.8.0
      - save_cache:
          key: v2-dep-sgk_web-{{ checksum "package.json" }}
          paths:
          # This is a broad list of cache paths to include many possible development environments
          # You can probably delete some of these entries
          - vendor/bundle
          - ~/virtualenvs
          - ~/.m2
          - ~/.ivy2
          - ~/.bundle
          - ~/.go_workspace
          - ~/.gradle
          - ~/.cache/bower
          # These cache paths were specified in the 1.0 config
          - node_modules
          - ./node_modules
          - /root/.cache/Cypress

      - run: npm run serv & npm run cyp
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test
