version: 2

jobs:
  build-and-test:
    docker:
      - image: cypress/browsers:node8.9.3-npm6.10.1-chrome75
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dep-sgk_web-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dep-sgk_web-{{ checksum "package.json" }}
          paths:
          # This is a broad list of cache paths to include many possible development environments
          # You can probably delete some of these entries
          - vendor/bundle
          - ~/virtualenvs
          - ~/.m2
          - ~/.ivy2
          - ~/.bundle
          - ~/.go_workspace
          - ~/.gradle
          - ~/.cache/bower
          # These cache paths were specified in the 1.0 config
          - node_modules
          - ./node_modules
          - /root/.cache/Cypress
      - run: npm run serv & npm run cyp
workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test
